image: ghcr.io/cirruslabs/flutter:3.16.9

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

stages:
  - deploy

pages:
  stage: deploy
  before_script:
    - cd counterexample
    - flutter pub get
  script:
    - flutter build web --release
    - cp -r build/web ../public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"